[2022-09-09T16:44:59.641+0000] {processor.py:153} INFO - Started process (PID=12593) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:44:59.642+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:44:59.643+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:44:59.643+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:45:29.644+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:45:29.644+0000] {timeout.py:67} ERROR - Process timed out, PID: 12593
[2022-09-09T16:45:50.209+0000] {processor.py:153} INFO - Started process (PID=13081) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:45:50.227+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:45:50.227+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:45:50.227+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:46:20.228+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:46:20.228+0000] {timeout.py:67} ERROR - Process timed out, PID: 13081
[2022-09-09T16:46:45.530+0000] {processor.py:153} INFO - Started process (PID=13639) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:46:45.617+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:46:45.618+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:46:45.618+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:47:22.122+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:47:22.121+0000] {timeout.py:67} ERROR - Process timed out, PID: 13639
[2022-09-09T16:47:36.252+0000] {processor.py:153} INFO - Started process (PID=14126) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:47:36.252+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:47:36.253+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:47:36.253+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:48:06.254+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:48:06.254+0000] {timeout.py:67} ERROR - Process timed out, PID: 14126
[2022-09-09T16:48:27.437+0000] {processor.py:153} INFO - Started process (PID=14629) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:48:27.438+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:48:27.438+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:48:27.438+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:48:57.439+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:48:57.439+0000] {timeout.py:67} ERROR - Process timed out, PID: 14629
[2022-09-09T16:49:20.845+0000] {processor.py:153} INFO - Started process (PID=15173) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:49:20.846+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:49:20.847+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:49:20.846+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:49:50.848+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:49:50.847+0000] {timeout.py:67} ERROR - Process timed out, PID: 15173
[2022-09-09T16:50:12.574+0000] {processor.py:153} INFO - Started process (PID=15808) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:50:12.575+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:50:12.575+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:50:12.575+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:50:42.576+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:50:42.576+0000] {timeout.py:67} ERROR - Process timed out, PID: 15808
[2022-09-09T16:51:03.473+0000] {processor.py:153} INFO - Started process (PID=16504) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:51:03.474+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:51:03.474+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:51:03.474+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:51:33.476+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:51:33.475+0000] {timeout.py:67} ERROR - Process timed out, PID: 16504
[2022-09-09T16:51:54.569+0000] {processor.py:153} INFO - Started process (PID=17064) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:51:54.569+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:51:54.570+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:51:54.570+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:52:24.571+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:52:24.571+0000] {timeout.py:67} ERROR - Process timed out, PID: 17064
[2022-09-09T16:52:45.407+0000] {processor.py:153} INFO - Started process (PID=17637) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:52:45.407+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:52:45.408+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:52:45.408+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:53:15.410+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:53:15.409+0000] {timeout.py:67} ERROR - Process timed out, PID: 17637
[2022-09-09T16:53:49.576+0000] {processor.py:153} INFO - Started process (PID=18202) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:53:49.577+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:53:49.577+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:53:49.577+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:54:19.580+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:54:19.579+0000] {timeout.py:67} ERROR - Process timed out, PID: 18202
[2022-09-09T16:54:41.751+0000] {processor.py:153} INFO - Started process (PID=18898) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:54:41.794+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:54:41.794+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:54:41.794+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:55:11.796+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:55:11.795+0000] {timeout.py:67} ERROR - Process timed out, PID: 18898
[2022-09-09T16:55:32.580+0000] {processor.py:153} INFO - Started process (PID=19383) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:55:32.593+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:55:32.594+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:55:32.593+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:56:02.595+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:56:02.594+0000] {timeout.py:67} ERROR - Process timed out, PID: 19383
[2022-09-09T16:56:23.105+0000] {processor.py:153} INFO - Started process (PID=20164) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:56:23.106+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:56:23.106+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:56:23.106+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:56:53.107+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:56:53.107+0000] {timeout.py:67} ERROR - Process timed out, PID: 20164
[2022-09-09T16:57:13.706+0000] {processor.py:153} INFO - Started process (PID=20768) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:57:13.707+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:57:13.707+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:57:13.707+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:57:43.709+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:57:43.708+0000] {timeout.py:67} ERROR - Process timed out, PID: 20768
[2022-09-09T16:58:14.416+0000] {processor.py:153} INFO - Started process (PID=21318) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:58:14.417+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:58:14.417+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:58:14.417+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:59:01.013+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:01.013+0000] {timeout.py:67} ERROR - Process timed out, PID: 21318
[2022-09-09T16:59:01.018+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:01.014+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 21318
[2022-09-09T16:59:01.018+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:01.018+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T16:59:01.085+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:01.084+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 21318

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T16:59:01.086+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:01.086+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T16:59:01.087+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:01.086+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 9, in <module>
    ips = spark.read.format("csv").option("header","true").load("file:///opt/airflow/dags/spark_jobs/dados/bronze/ips.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 177, in load
    return self._df(self._jreader.load(path))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o26.load
[2022-09-09T16:59:01.087+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:59:04.941+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/atividade_2.py took 50.528 seconds
[2022-09-09T16:59:05.908+0000] {processor.py:153} INFO - Started process (PID=21650) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T16:59:05.909+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T16:59:05.909+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:05.909+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:59:36.413+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:36.413+0000] {timeout.py:67} ERROR - Process timed out, PID: 21650
[2022-09-09T16:59:36.414+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:36.413+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 21650
[2022-09-09T16:59:36.414+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:36.414+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T16:59:36.415+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:36.414+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 21650

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T16:59:36.415+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:36.415+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T16:59:36.416+0000] {logging_mixin.py:115} INFO - [2022-09-09T16:59:36.415+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 9, in <module>
    ips = spark.read.format("csv").option("header","true").load("file:///opt/airflow/dags/spark_jobs/dados/bronze/ips.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 177, in load
    return self._df(self._jreader.load(path))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o26.load
[2022-09-09T16:59:36.416+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T16:59:36.469+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/atividade_2.py took 30.563 seconds
[2022-09-09T17:00:11.391+0000] {processor.py:153} INFO - Started process (PID=22357) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:00:11.445+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:00:11.446+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:00:11.446+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:00:41.447+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:00:41.447+0000] {timeout.py:67} ERROR - Process timed out, PID: 22357
[2022-09-09T17:01:02.983+0000] {processor.py:153} INFO - Started process (PID=23141) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:01:02.984+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:01:02.985+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:01:02.984+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:01:48.890+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:01:48.890+0000] {timeout.py:67} ERROR - Process timed out, PID: 23141
[2022-09-09T17:02:03.870+0000] {processor.py:153} INFO - Started process (PID=23863) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:02:03.909+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:02:03.909+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:02:03.909+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:02:33.910+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:02:33.910+0000] {timeout.py:67} ERROR - Process timed out, PID: 23863
[2022-09-09T17:02:54.265+0000] {processor.py:153} INFO - Started process (PID=24526) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:02:54.299+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:02:54.299+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:02:54.299+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:03:24.300+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:03:24.300+0000] {timeout.py:67} ERROR - Process timed out, PID: 24526
[2022-09-09T17:03:46.185+0000] {processor.py:153} INFO - Started process (PID=25366) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:03:46.203+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:03:46.204+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:03:46.204+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:04:16.205+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:04:16.205+0000] {timeout.py:67} ERROR - Process timed out, PID: 25366
[2022-09-09T17:04:38.422+0000] {processor.py:153} INFO - Started process (PID=26414) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:04:38.423+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:04:38.423+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:04:38.423+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:05:08.424+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:05:08.424+0000] {timeout.py:67} ERROR - Process timed out, PID: 26414
[2022-09-09T17:05:29.260+0000] {processor.py:153} INFO - Started process (PID=27095) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:05:29.260+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:05:29.261+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:05:29.261+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:05:59.262+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:05:59.262+0000] {timeout.py:67} ERROR - Process timed out, PID: 27095
[2022-09-09T17:06:19.285+0000] {processor.py:153} INFO - Started process (PID=27944) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:06:19.286+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:06:19.286+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:06:19.286+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:06:49.287+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:06:49.287+0000] {timeout.py:67} ERROR - Process timed out, PID: 27944
[2022-09-09T17:07:10.929+0000] {processor.py:153} INFO - Started process (PID=28963) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:07:10.930+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:07:10.930+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:07:10.930+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:07:40.931+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:07:40.931+0000] {timeout.py:67} ERROR - Process timed out, PID: 28963
[2022-09-09T17:08:01.603+0000] {processor.py:153} INFO - Started process (PID=29761) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:08:01.603+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:08:01.604+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:08:01.604+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:08:31.605+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:08:31.605+0000] {timeout.py:67} ERROR - Process timed out, PID: 29761
[2022-09-09T17:08:52.073+0000] {processor.py:153} INFO - Started process (PID=30513) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:08:52.073+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:08:52.074+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:08:52.074+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:09:22.075+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:09:22.075+0000] {timeout.py:67} ERROR - Process timed out, PID: 30513
[2022-09-09T17:09:43.016+0000] {processor.py:153} INFO - Started process (PID=31572) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:09:43.017+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:09:43.017+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:09:43.017+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:10:13.018+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:10:13.018+0000] {timeout.py:67} ERROR - Process timed out, PID: 31572
[2022-09-09T17:11:18.653+0000] {processor.py:153} INFO - Started process (PID=312) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:11:18.736+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:11:18.736+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:11:18.736+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:13:47.758+0000] {processor.py:153} INFO - Started process (PID=1197) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:13:48.663+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:13:48.664+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:13:48.663+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:14:18.665+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:14:18.664+0000] {timeout.py:67} ERROR - Process timed out, PID: 1197
[2022-09-09T17:14:39.200+0000] {processor.py:153} INFO - Started process (PID=2018) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:14:39.237+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:14:39.237+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:14:39.237+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:15:09.238+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:15:09.238+0000] {timeout.py:67} ERROR - Process timed out, PID: 2018
[2022-09-09T17:15:09.240+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:15:09.239+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 2018
[2022-09-09T17:15:09.240+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:15:09.240+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T17:15:09.241+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:15:09.240+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 2018

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T17:15:09.242+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:15:09.241+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T17:15:09.243+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:15:09.242+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 9, in <module>
    ips = spark.read.format("csv").option("header","true").load("file:///opt/airflow/dags/spark_jobs/dados/bronze/ips.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 177, in load
    return self._df(self._jreader.load(path))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o26.load
[2022-09-09T17:15:09.243+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:15:15.039+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/atividade_2.py took 35.841 seconds
[2022-09-09T17:15:45.756+0000] {processor.py:153} INFO - Started process (PID=2873) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:15:45.788+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:15:45.789+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:15:45.788+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:16:15.790+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:16:15.789+0000] {timeout.py:67} ERROR - Process timed out, PID: 2873
[2022-09-09T17:16:36.388+0000] {processor.py:153} INFO - Started process (PID=3871) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:16:36.528+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:16:36.529+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:16:36.529+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:17:06.530+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:17:06.530+0000] {timeout.py:67} ERROR - Process timed out, PID: 3871
[2022-09-09T17:17:48.198+0000] {processor.py:153} INFO - Started process (PID=4848) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:17:48.226+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:17:48.227+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:17:48.226+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:18:18.228+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:18:18.228+0000] {timeout.py:67} ERROR - Process timed out, PID: 4848
[2022-09-09T17:18:18.229+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:18:18.228+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 4848
[2022-09-09T17:18:18.229+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:18:18.229+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T17:18:18.230+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:18:18.230+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 4848

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T17:18:18.231+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:18:18.230+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T17:18:18.232+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:18:18.231+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 9, in <module>
    ips = spark.read.format("csv").option("header","true").load("file:///opt/airflow/dags/spark_jobs/dados/bronze/ips.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 177, in load
    return self._df(self._jreader.load(path))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o26.load
[2022-09-09T17:18:18.232+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:18:21.701+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/atividade_2.py took 33.507 seconds
[2022-09-09T17:20:33.368+0000] {processor.py:153} INFO - Started process (PID=5574) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:20:33.857+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:20:33.894+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:20:33.894+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:21:03.896+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:21:03.895+0000] {timeout.py:67} ERROR - Process timed out, PID: 5574
[2022-09-09T17:21:29.720+0000] {processor.py:153} INFO - Started process (PID=6535) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:21:29.856+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:21:29.857+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:21:29.856+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:21:59.858+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:21:59.857+0000] {timeout.py:67} ERROR - Process timed out, PID: 6535
[2022-09-09T17:22:22.521+0000] {processor.py:153} INFO - Started process (PID=7631) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:22:22.604+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:22:22.605+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:22:22.605+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:22:52.606+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:22:52.606+0000] {timeout.py:67} ERROR - Process timed out, PID: 7631
[2022-09-09T17:25:03.084+0000] {processor.py:153} INFO - Started process (PID=8726) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T17:25:03.483+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T17:25:03.484+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:25:03.483+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:25:33.485+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:25:33.484+0000] {timeout.py:67} ERROR - Process timed out, PID: 8726
[2022-09-09T17:25:33.486+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:25:33.485+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 8726
[2022-09-09T17:25:33.486+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:25:33.486+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T17:25:33.487+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:25:33.486+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 8726

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T17:25:33.487+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:25:33.487+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T17:25:33.488+0000] {logging_mixin.py:115} INFO - [2022-09-09T17:25:33.488+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 9, in <module>
    ips = spark.read.format("csv").option("header","true").load("file:///opt/airflow/dags/spark_jobs/dados/bronze/ips.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 177, in load
    return self._df(self._jreader.load(path))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o26.load
[2022-09-09T17:25:33.489+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T17:25:35.233+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/atividade_2.py took 32.152 seconds
[2022-09-09T18:42:16.880+0000] {processor.py:153} INFO - Started process (PID=55) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:42:21.034+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:42:21.035+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:42:21.035+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:43:37.817+0000] {processor.py:153} INFO - Started process (PID=372) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:43:37.849+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:43:37.850+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:43:37.849+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:44:07.851+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:44:07.851+0000] {timeout.py:67} ERROR - Process timed out, PID: 372
[2022-09-09T18:44:07.853+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:44:07.852+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 7, in <module>
    spark = SparkSession.builder.getOrCreate()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 195, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 417, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/java_gateway.py", line 103, in launch_gateway
    time.sleep(0.1)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 372
[2022-09-09T18:44:07.854+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:44:18.328+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/atividade_2.py took 40.514 seconds
[2022-09-09T18:45:05.669+0000] {processor.py:153} INFO - Started process (PID=700) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:45:05.733+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:45:05.734+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:45:05.733+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:45:35.735+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:45:35.735+0000] {timeout.py:67} ERROR - Process timed out, PID: 700
[2022-09-09T18:45:37.537+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:45:37.536+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 700
[2022-09-09T18:45:37.538+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:45:37.538+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T18:45:37.539+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:45:37.538+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 700

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T18:45:37.540+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:45:37.540+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T18:45:37.541+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:45:37.540+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 7, in <module>
    spark = SparkSession.builder.getOrCreate()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 208, in __init__
    udf_profiler_cls,
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 282, in _do_init
    self._jsc = jsc or self._initialize_context(self._conf._jconf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 402, in _initialize_context
    return self._jvm.JavaSparkContext(jconf)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1586, in __call__
    answer, self._gateway_client, None, self._fqn)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext
[2022-09-09T18:45:37.542+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:45:38.158+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/atividade_2.py took 32.492 seconds
[2022-09-09T18:46:08.203+0000] {processor.py:153} INFO - Started process (PID=1182) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:46:08.233+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:46:08.233+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:46:08.233+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:46:38.235+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:46:38.234+0000] {timeout.py:67} ERROR - Process timed out, PID: 1182
[2022-09-09T18:46:59.362+0000] {processor.py:153} INFO - Started process (PID=1965) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:46:59.398+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:46:59.398+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:46:59.398+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:47:29.400+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:47:29.399+0000] {timeout.py:67} ERROR - Process timed out, PID: 1965
[2022-09-09T18:47:54.018+0000] {processor.py:153} INFO - Started process (PID=2512) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:47:54.159+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:47:54.160+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:47:54.159+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:48:24.161+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:48:24.160+0000] {timeout.py:67} ERROR - Process timed out, PID: 2512
[2022-09-09T18:48:44.191+0000] {processor.py:153} INFO - Started process (PID=3113) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:48:44.241+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:48:44.241+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:48:44.241+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:49:14.243+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:49:14.242+0000] {timeout.py:67} ERROR - Process timed out, PID: 3113
[2022-09-09T18:49:15.230+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:49:15.229+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 3113
[2022-09-09T18:49:15.230+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:49:15.230+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T18:49:15.231+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:49:15.230+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 3113

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T18:49:15.231+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:49:15.231+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T18:49:15.232+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:49:15.231+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 9, in <module>
    ips = spark.read.format("csv").option("header","true").load("file:///opt/airflow/dags/spark_jobs/dados/bronze/ips.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 177, in load
    return self._df(self._jreader.load(path))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o26.load
[2022-09-09T18:49:15.232+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:49:15.778+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/atividade_2.py took 31.590 seconds
[2022-09-09T18:49:46.355+0000] {processor.py:153} INFO - Started process (PID=3708) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:49:46.372+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:49:46.372+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:49:46.372+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:50:18.236+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:50:18.236+0000] {timeout.py:67} ERROR - Process timed out, PID: 3708
[2022-09-09T18:50:18.238+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:50:18.237+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 3708
[2022-09-09T18:50:18.252+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:50:18.252+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T18:50:18.253+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:50:18.252+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 3708

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T18:50:18.253+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:50:18.253+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T18:50:18.254+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:50:18.253+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 9, in <module>
    ips = spark.read.format("csv").option("header","true").load("file:///opt/airflow/dags/spark_jobs/dados/bronze/ips.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 177, in load
    return self._df(self._jreader.load(path))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o26.load
[2022-09-09T18:50:18.254+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:50:49.350+0000] {processor.py:153} INFO - Started process (PID=4030) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:50:49.407+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:50:49.407+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:50:49.407+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:52:03.441+0000] {processor.py:153} INFO - Started process (PID=4624) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:52:03.571+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:52:03.572+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:52:03.572+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:52:33.573+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:52:33.573+0000] {timeout.py:67} ERROR - Process timed out, PID: 4624
[2022-09-09T18:52:53.932+0000] {processor.py:153} INFO - Started process (PID=5358) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:52:54.012+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:52:54.012+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:52:54.012+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:53:24.013+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:53:24.013+0000] {timeout.py:67} ERROR - Process timed out, PID: 5358
[2022-09-09T18:53:44.467+0000] {processor.py:153} INFO - Started process (PID=5902) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:53:44.543+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:53:44.544+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:53:44.543+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:54:14.546+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:54:14.545+0000] {timeout.py:67} ERROR - Process timed out, PID: 5902
[2022-09-09T18:54:34.798+0000] {processor.py:153} INFO - Started process (PID=6714) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:54:34.842+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:54:34.927+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:54:34.927+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:55:05.616+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:55:05.616+0000] {timeout.py:67} ERROR - Process timed out, PID: 6714
[2022-09-09T18:55:25.781+0000] {processor.py:153} INFO - Started process (PID=7295) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:55:25.873+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:55:25.874+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:55:25.874+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:55:55.875+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:55:55.875+0000] {timeout.py:67} ERROR - Process timed out, PID: 7295
[2022-09-09T18:56:16.202+0000] {processor.py:153} INFO - Started process (PID=7843) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:56:16.255+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:56:16.256+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:56:16.256+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:56:46.408+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:56:46.408+0000] {timeout.py:67} ERROR - Process timed out, PID: 7843
[2022-09-09T18:56:46.409+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:56:46.408+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 7843
[2022-09-09T18:56:46.409+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:56:46.409+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T18:56:46.410+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:56:46.410+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 7843

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T18:56:46.411+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:56:46.410+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T18:56:46.411+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:56:46.411+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 9, in <module>
    ips = spark.read.format("csv").option("header","true").load("file:///opt/airflow/dags/spark_jobs/dados/bronze/ips.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 177, in load
    return self._df(self._jreader.load(path))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o26.load
[2022-09-09T18:56:46.412+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:56:47.386+0000] {processor.py:161} INFO - Processing /opt/airflow/dags/atividade_2.py took 31.187 seconds
[2022-09-09T18:57:17.546+0000] {processor.py:153} INFO - Started process (PID=8432) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:57:17.553+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:57:17.554+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:57:17.554+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:57:47.557+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:57:47.556+0000] {timeout.py:67} ERROR - Process timed out, PID: 8432
[2022-09-09T18:58:08.529+0000] {processor.py:153} INFO - Started process (PID=9169) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:58:08.640+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:58:08.641+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:58:08.641+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:58:38.643+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:58:38.642+0000] {timeout.py:67} ERROR - Process timed out, PID: 9169
[2022-09-09T18:59:01.585+0000] {processor.py:153} INFO - Started process (PID=9983) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T18:59:01.586+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T18:59:01.586+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:59:01.586+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T18:59:31.588+0000] {logging_mixin.py:115} INFO - [2022-09-09T18:59:31.587+0000] {timeout.py:67} ERROR - Process timed out, PID: 9983
[2022-09-09T19:00:00.734+0000] {processor.py:153} INFO - Started process (PID=10563) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:00:00.735+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:00:00.735+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:00:00.735+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:00:30.736+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:00:30.736+0000] {timeout.py:67} ERROR - Process timed out, PID: 10563
[2022-09-09T19:00:57.226+0000] {processor.py:153} INFO - Started process (PID=11141) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:00:57.226+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:00:57.227+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:00:57.227+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:01:27.228+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:01:27.228+0000] {timeout.py:67} ERROR - Process timed out, PID: 11141
[2022-09-09T19:02:09.230+0000] {processor.py:153} INFO - Started process (PID=11869) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:02:09.348+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:02:09.349+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:02:09.349+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:02:39.350+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:02:39.350+0000] {timeout.py:67} ERROR - Process timed out, PID: 11869
[2022-09-09T19:03:20.785+0000] {processor.py:153} INFO - Started process (PID=12401) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:03:22.697+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:03:22.699+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:03:22.699+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:03:52.702+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:03:52.702+0000] {timeout.py:67} ERROR - Process timed out, PID: 12401
[2022-09-09T19:04:11.026+0000] {processor.py:153} INFO - Started process (PID=13186) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:04:11.026+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:04:11.027+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:04:11.027+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:04:41.028+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:04:41.028+0000] {timeout.py:67} ERROR - Process timed out, PID: 13186
[2022-09-09T19:05:01.179+0000] {processor.py:153} INFO - Started process (PID=13791) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:05:01.179+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:05:01.180+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:05:01.180+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:05:43.555+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:05:43.555+0000] {timeout.py:67} ERROR - Process timed out, PID: 13791
[2022-09-09T19:05:53.890+0000] {processor.py:153} INFO - Started process (PID=14371) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:05:53.891+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:05:53.892+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:05:53.892+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:06:23.893+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:06:23.893+0000] {timeout.py:67} ERROR - Process timed out, PID: 14371
[2022-09-09T19:06:23.895+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:06:23.894+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 14371
[2022-09-09T19:06:23.895+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:06:23.895+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T19:06:23.896+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:06:23.895+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 14371

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T19:06:23.896+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:06:23.896+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T19:06:23.897+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:06:23.897+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 7, in <module>
    spark = SparkSession.builder.getOrCreate()
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/session.py", line 269, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 483, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 208, in __init__
    udf_profiler_cls,
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 282, in _do_init
    self._jsc = jsc or self._initialize_context(self._conf._jconf)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/context.py", line 402, in _initialize_context
    return self._jvm.JavaSparkContext(jconf)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1586, in __call__
    answer, self._gateway_client, None, self._fqn)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling None.org.apache.spark.api.java.JavaSparkContext
[2022-09-09T19:06:23.897+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:07:18.683+0000] {processor.py:153} INFO - Started process (PID=14673) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:07:18.889+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:07:18.889+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:07:18.889+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:07:48.890+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:07:48.890+0000] {timeout.py:67} ERROR - Process timed out, PID: 14673
[2022-09-09T19:08:16.994+0000] {processor.py:153} INFO - Started process (PID=15360) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:08:17.047+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:08:17.048+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:08:17.048+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:08:47.832+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:08:47.831+0000] {timeout.py:67} ERROR - Process timed out, PID: 15360
[2022-09-09T19:08:47.833+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:08:47.832+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 15360
[2022-09-09T19:08:47.834+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:08:47.833+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T19:08:47.835+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:08:47.834+0000] {java_gateway.py:1056} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 68, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/atividade_2.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.3.4/best-practices.html#reducing-dag-complexity, PID: 15360

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/clientserver.py", line 540, in send_command
    "Error while sending or receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2022-09-09T19:08:47.835+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:08:47.835+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2022-09-09T19:08:47.836+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:08:47.835+0000] {dagbag.py:321} ERROR - Failed to import: /opt/airflow/dags/atividade_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 318, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/atividade_2.py", line 9, in <module>
    ips = spark.read.format("csv").option("header","true").load("file:///opt/airflow/dags/spark_jobs/dados/bronze/ips.csv")
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/readwriter.py", line 177, in load
    return self._df(self._jreader.load(path))
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/java_gateway.py", line 1322, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/home/airflow/.local/lib/python3.7/site-packages/pyspark/sql/utils.py", line 190, in deco
    return f(*a, **kw)
  File "/home/airflow/.local/lib/python3.7/site-packages/py4j/protocol.py", line 336, in get_return_value
    format(target_id, ".", name))
py4j.protocol.Py4JError: An error occurred while calling o26.load
[2022-09-09T19:08:47.836+0000] {processor.py:652} WARNING - No viable dags retrieved from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:09:16.581+0000] {processor.py:153} INFO - Started process (PID=15745) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:09:16.582+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:09:16.582+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:09:16.582+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:11:25.598+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:11:25.598+0000] {timeout.py:67} ERROR - Process timed out, PID: 15745
[2022-09-09T19:11:54.239+0000] {processor.py:153} INFO - Started process (PID=16268) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:11:54.240+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:11:54.240+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:11:54.240+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:12:24.242+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:12:24.241+0000] {timeout.py:67} ERROR - Process timed out, PID: 16268
[2022-09-09T19:12:48.431+0000] {processor.py:153} INFO - Started process (PID=16805) to work on /opt/airflow/dags/atividade_2.py
[2022-09-09T19:12:48.432+0000] {processor.py:640} INFO - Processing file /opt/airflow/dags/atividade_2.py for tasks to queue
[2022-09-09T19:12:48.432+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:12:48.432+0000] {dagbag.py:508} INFO - Filling up the DagBag from /opt/airflow/dags/atividade_2.py
[2022-09-09T19:13:18.433+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:13:18.433+0000] {timeout.py:67} ERROR - Process timed out, PID: 16805
[2022-09-09T19:13:38.753+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:13:38.753+0000] {process_utils.py:240} INFO - Waiting up to 5 seconds for processes to exit...
[2022-09-09T19:13:41.304+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:13:41.304+0000] {process_utils.py:240} INFO - Waiting up to 5 seconds for processes to exit...
[2022-09-09T19:13:43.780+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:13:43.780+0000] {process_utils.py:240} INFO - Waiting up to 5 seconds for processes to exit...
[2022-09-09T19:13:48.759+0000] {logging_mixin.py:115} INFO - [2022-09-09T19:13:48.759+0000] {process_utils.py:240} INFO - Waiting up to 5 seconds for processes to exit...
